### ISSUE TITLE
태그가 히토미 이헨과 다르게 누락되있는 경우

### ISSUE THREAD

**Issue by EDD1802** [rollrat/koromo-copy-windows#23]
https://hitomi.la/galleries/1467093.html

  간혹 태그가 히토미 이헨과 다르게 누락되어서, 위 경우에는 female:scat 이 제대로 달려있지 않아 프로그램 상에서 해당 태그로 검색이 불가한듯 합니다. 이런 식으로 항목 자체는 제목이나 작가로 찾을 수 있으나 태그가 맞지 않는 경우가 있는 듯 한데 해결 방법이 있을까요?? 
  프로그램 개발 중지 소식이 들려서 정말 아쉽지만 앞으로도 잘 사용하겠습니다 감사합니다.

**Comment by dc-koromo** [comment]
데이터를 처음부터 다시 동기화시키는 방법밖엔 없을 것 같네요
주말에 해결해 둘께요

**Comment by EDD1802** [comment]
고생 많으십니다 감사드립니다.
