### ISSUE TITLE
"설정-다운로더-히토미-제외할 태그"에 관해서 여쭤봅니다

### ISSUE THREAD

**Issue by hangle7** [rollrat/koromo-copy-windows#24]
어떻게 해야 태그가 제외되는거죠? ,를 넣어도 띄어쓰기를 해도 안되네요

**Comment by dc-koromo** [comment]
프로그램을 처음으로 실행했을때 기본적으로 있던 형식과 같습니다.
female:mother, male:anal, male:guro, female:guro, male:snuff, female:snuff
이런식으로 명시적으로 써주세요
