### ISSUE TITLE
수동 업데이트가 되지 않습니다. 같은 현상 입니다.

### ISSUE THREAD

**Issue by KiwiCube** [rollrat/koromo-copy-windows#27]
콘솔툴 에서 위의 님과 같은 현상으로 404 에러가 쭈욱 뜨는데 혹시 그것 때문인가요?
시작 -> 합치기 -> 닫기버튼 -> 콘솔창에서 엔터 -> 콘솔 프롬프트에서 hutomi -test 8 -> exit 로 종료
그리고 다시 시작해서 search:0-25 해도 9월 13일 이후는 나오지 않네요.

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/releases/tag/1.16.7182.36052x64 이걸로 다시시도해보세요
