### ISSUE TITLE
머지합치기 이후에 수동업데이트 에러 현상

### ISSUE THREAD

**Issue by EDD1802** [rollrat/koromo-copy-windows#28]
안녕하세요 바쁘실텐데 신경쓰시게 만들어 죄송합니다.
머지합치기 이후에 다시 콘솔창으로 돌아가서 hitomi -test 8을 입력하면,

dc-koromo@koromo-copy:~$ hitomi -test 8
Error occurred on processing!
Message: 'System.OutOfMemoryException' 형식의 예외가 Throw되었습니다.
StackTrace:    위치: System.Text.StringBuilder.ToString()
   위치: System.IO.StreamReader.ReadToEnd()
   위치: System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   위치: System.IO.File.ReadAllText(String path)
   위치: Koromo_Copy.Component.Hitomi.HitomiData.LoadMetadataJson() 파일 C:\Dev\koromo-copy\Koromo Copy\Component\Hitomi\HitomiData.cs:줄 121
   위치: Koromo_Copy.Console.HitomiConsole.ProcessTest(String[] args) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 665
   위치: Koromo_Copy.Console.HitomiConsole.Redirect(String[] arguments, String contents) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 226
   위치: Koromo_Copy.Console.HitomiConsole.Koromo_Copy.Interface.IConsole.Redirect(String[] arguments, String contents) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 234
   위치: Koromo_Copy.Console.Console.<Loop>b__46_0() 파일 C:\Dev\koromo-copy\Koromo Copy\Console\Console.cs:줄 377

대체적으로 위와 같은 에러가 나오면서 업데이트가 되지 않는데, 
이 상태에서 종료를 한뒤 run gbt 합치기를 하지 않고 hitomi -test 8을 실행했을 시에는

Error occurred on processing!
Message: 'System.OutOfMemoryException' 형식의 예외가 Throw되었습니다.
StackTrace:    위치: MessagePack.MessagePackBinary.FastResize(Byte[]& array, Int32 newSize)
   위치: MessagePack.MessagePackBinary.WriteString(Byte[]& bytes, Int32 offset, String value)
   위치: MessagePack.Formatters.NullableStringFormatter.Serialize(Byte[]& bytes, Int32 offset, String value, IFormatterResolver typeResolver)
   위치: MessagePack.Formatters.Koromo_Copy_Component_Hitomi_HitomiIndexMetadataFormatter3.Serialize(Byte[]& , Int32 , HitomiIndexMetadata , IFormatterResolver )
   위치: MessagePack.Formatters.ListFormatter`1.Serialize(Byte[]& bytes, Int32 offset, List`1 value, IFormatterResolver formatterResolver)
   위치: MessagePack.Formatters.Koromo_Copy_Component_Hitomi_HitomiIndexDataModelFormatter1.Serialize(Byte[]& , Int32 , HitomiIndexDataModel , IFormatterResolver )
   위치: MessagePack.MessagePackSerializer.Serialize[T](T obj, IFormatterResolver resolver)
   위치: Koromo_Copy.Component.Hitomi.HitomiIndex.MakeIndex() 파일 C:\Dev\koromo-copy\Koromo Copy\Component\Hitomi\HitomiIndex.cs:줄 156
   위치: Koromo_Copy.Console.HitomiConsole.ProcessTest(String[] args) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 672
   위치: Koromo_Copy.Console.HitomiConsole.Redirect(String[] arguments, String contents) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 226
   위치: Koromo_Copy.Console.HitomiConsole.Koromo_Copy.Interface.IConsole.Redirect(String[] arguments, String contents) 파일 C:\Dev\koromo-copy\Koromo Copy\Console\HitomiConsole.cs:줄 234
   위치: Koromo_Copy.Console.Console.<Loop>b__46_0() 파일 C:\Dev\koromo-copy\Koromo Copy\Console\Console.cs:줄 377

  라는 새로운 오류가 뜨거나, 혹은 처음과 같은 오류가 다시 나오면서 업데이트가 되지 않습니다. 그런데 이걸 여러번 시도 하다보면, 즉 run gbt 합치기를 한 다음 프로그램을 종료하고 다시 실행 하여 hitomi -test 8 입력하는 걸 열댓번쯤 반복하다보면 어느 순간 오류가 나오지 않으면서 업데이트가 되는 듯 합니다. 이럴 경우에는 합치기를 한뒤 프로그램을 종료했기 때문에 그 항목이 반영되지 않게 되나요?? 

  어쨌든 대부분의 시행에서 저 오류가 나오다가 그냥 어쩔때는 작동하는듯 합니다. 여러번 시도 해본 결과 개인적으로 규칙을 발견하지는 못하였지만 run gbt 합치기 이후 종료를 하지 않은 창에서 hitomi -test 8 이 작동한 경우는 한 번도 없었습니다. 해결이 간단한 문제라면 원인을 찾을 수 있었으면 좋겠습니다ㅜㅜ 감사합니다.

**Comment by dc-koromo** [comment]
hitomi -test 8을 할 때 모든 메타데이터와 동기화된 데이터를 불러오는데 이 작업을 수행하려면 2GB가 넘는 메모리가 필요합니다. OutOfMemoryException오류는 프로그램이 사용할 수 있는 메모리 용량을 초과해서 발생하는 오류입니다. 32bit 버전인 기존 프로그램은 최대 2GB 까지만 사용 가능하니 더 많은 메모리를 사용하려면 https://github.com/dc-koromo/koromo-copy/releases/tag/1.16.7182.36052x64 이 버전을 사용해 주세요.
기존폴더에 넣어서 사용하심 됩니다.

**Comment by EDD1802** [comment]
폴더에 넣고 실행해보니 문제 없이 잘 작동합니다. 개발 종료 하셨는데 찾아오셔서 답변 해주신 것에 정말로 감사드립니다! 궁금한 점이 있는데 그 gbt와 원래 제목 동기화는 용도가 어떤 것인가요?? gbt는 누락된 갤러리를 찾는 거라서 혹시 프로그램에서 서치 안되는 갤러리가 있다면 번호를 앞서 1번부터 넣고 쭉 돌린 다음 합치면 검색에서 노출되게 만들 수 있는 것인지요. 번호가 자동으로 최신 갤러리 쪽으로 설정되는것 같던데 지금까지 안 돌린 부분을 따로 지정해서 검색할 필요가 있을까요??

**Comment by dc-koromo** [comment]
gbt는 말씀하신 그대로 동작합니다. 1부터 돌리게 되면 누락된 작품들도 찾을 수 있을꺼예요.

원래 제목 동기화 기능은 히토미 작품들의 원 출처인 이/익헨에서 제공하는 작품 제목을 가져와 적용시키는 기능입니다. 히토미는 이/익헨 자료를 미러링할때 제목을 수정하는데, 수정된 제목에는 작품 출처, 작가, 그룹, 언어 정보가 빠지게 됩니다. 원래 제목 동기화를 사용하면 히토미에서 수정된 제목대신 이/익헨 제목을 사용해 제목의 무결성이 보장됩니다.

**Comment by EDD1802** [comment]
아 그렇군요 그럼 만약 태그가 상이하게 나오는 것도 gbt를 돌리면 수정이 될까요? 친절하게 답변 해주셔서 정말 감사합니다ㅠㅠ 코로모 다운로더 편의성이 좋아서 다른 프로그램은 못 쓰겠네요 언제나 잘 이용하고 있습니다.
