### ISSUE TITLE
실행하면 Setting.json 파일만 생기고 다운로더가 안켜집니다.

### ISSUE THREAD

**Issue by hhm1573** [rollrat/koromo-copy-windows#30]
10월30일에 릴리즈된 버전을 다운받아서 실행했는데 Setting.json 파일만 생기고 아무런 반응이 없습니다.
관리자 권한으로 실행해도 마찬가지입니다...

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy-old/releases/download/2019.10.30/koromo-copy-readme2.txt
이거 다운로드해서 넣어주세요
레포지토리 이름을 바꿔서 실행 오류가 생기네요
