### ISSUE TITLE
다운로드시 파일형식이 chrome html document 가 됨

### ISSUE THREAD

**Issue by 1000taetae** [rollrat/koromo-copy-windows#31]
이거 윈도우 기본 이미지 뷰어로 열려면 어떻게 해야합니까?

**Comment by dc-koromo** [comment]
webp 파일말하시는건가요?
직접 jpg, png 파일등으로 변환하거나 다른 이미지 뷰어를 쓰세요
이미지파일변환은 병목이 너무 커요
