### ISSUE TITLE
버벅임&오류메시지

### ISSUE THREAD

**Issue by hashback1** [rollrat/koromo-copy-windows#36]
![제목 없음](https://user-images.githubusercontent.com/57169674/71610221-7b4d2000-2bd2-11ea-9c48-92b7b14f2d06.png)

어제 11시쯤부터 갑자기 렉 오지게 걸리면서 먹통되기 시작했는데
그 이후로 검색하면 썸네일도 바로 안뜨고 버벅거리고
작가검색으로 들어가면 어제는 뜨지도 않던 경고메시지도 주르륵 뜨네요

**Comment by dc-koromo** [comment]
확인결과 제 컴퓨터에선 문제가 없었어요
goodbyedpi나 VPN 켜놓고 사용중인거 맞죠?

**Comment by hashback1** [comment]
> 확인결과 제 컴퓨터에선 문제가 없었어요
> goodbyedpi나 VPN 켜놓고 사용중인거 맞죠?

아 DPI가 문제였구나...생각해보니 재부팅 이후에 저리된거같음
다시 해보니까 잘 되네요 고마워오

**Comment by hashback1** [comment]
> 확인결과 제 컴퓨터에선 문제가 없었어요
> goodbyedpi나 VPN 켜놓고 사용중인거 맞죠?

저 잘되다가 갑자기 시작할때 '데이터를 다운로드 중입니다...'가 무한으로 돌아서 검색 자체가 안되는데 이것도 제 문제려나요
