### ISSUE TITLE
예전 파일을 받을 때 날짜가 건너뛰어지는 현상

### ISSUE THREAD

**Issue by kkookko12** [rollrat/koromo-copy-windows#37]
![제목 없음](https://user-images.githubusercontent.com/54948314/71623992-8bd9b680-2c23-11ea-947f-00b9b51d491b.png)
항상 이 날짜 간격이 고정되는 건 아니구요, 새로 koromo copy 를 받아서 새 폴더에 넣었더니 12월 17일에서 9월로 건너뛰어지고, 원래 쓰던 폴더에 넣었더니 12월 21일에서 또 9월로 건너뛰어지더라구요...
건너뛰어지면 꼭 저 9월 날짜부터 나타나네요.
한동안 못 받아서 전 파일들을 받고 싶은데 중간이 생략되어버리니 답답해요!

**Comment by dc-koromo** [comment]
log.txt를 올려주세요

**Comment by kkookko12** [comment]
[koromomo.zip](https://github.com/dc-koromo/koromo-copy-windows/files/4014124/koromomo.zip)
로그입니다

**Comment by dc-koromo** [comment]
데이터가 누락된것 같아요
이유를 알 수가 없네요
[index-metadata.zip](https://github.com/dc-koromo/koromo-copy-windows/files/4015479/index-metadata.zip)
일단 이걸로 다시시도 해보세요

**Comment by kkookko12** [comment]
해결 됐어요! 감사합니다!!

**Comment by kkookko12** [comment]
[log.zip](https://github.com/dc-koromo/koromo-copy-windows/files/4070327/log.zip)
여전히 파일을 넘기다보면 중간에 9월 2일로 건너 뛰어지는 같은 현상이 발생합니다.
심지어 koromo copy 파일을 새로 받아서 고쳐졌었던 빈 파일만 받아지고 넘어가는 현상도 재발했어요...ㅜㅜ

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy-windows/releases/download/1.18/Koromo.Copy.exe
이거 써주세요

**Comment by kkookko12** [comment]
올려주신 파일을 사용해도 9월 2일로 건너뛰는 현상이 계속 발생하여 혹시나 제가 파일을 갱신하는 방법이 잘못 되었는지 질문드립니다.
https://github.com/dc-koromo/e-archive/releases/tag/L 에서 EHentaiArchive.zip 를 다운 - 압축 풀어서 koromocopy가 있는 폴더에 hiddendata와 index-metadata를 덮어쓰기 - 코로모 카피 켜고 run gbt - 시작 - 합치기 - 종료 후 hitomi -test 8 / hitomi -test 10 - koromocopy 재실행
