### ISSUE TITLE
데이터 다운로드 무한로딩

### ISSUE THREAD

**Issue by hashback1** [rollrat/koromo-copy-windows#38]
프로그램 실행하면 '데이터를 다운로드 중입니다...' 문구만 뜨고 계속 로딩중이네요

바로 데이터 받기 완료될때도 있는데 무한로딩 걸릴때가 더 많습니다...왜 이러는걸까요

dpi는 켜고 있습니다

+)혹시 검색화면 썸네일에 북마크된 작가가 표시되는 기능 넣어주실 수 있나요? 태그 하나 잡고 옛날거부터 돌면서 작가 검색 옵션을 통해 작가별로 옛날~최근꺼 가리지 않고 한번에 받는 식으로 파밍 중인데......워낙 작가들이 많으니 이미 받았던건지 안받았던건지 작가 검색 옵션을 쓰지 않는 이상 검색 화면에서는 파악하기 힘들더라구요

**Comment by dc-koromo** [comment]
데이터 다운로드는 index-metadata.compress라는 작품들의 모든 정보를 담고있는 파일을 다운로드하는 거예요
github에서 직접 내려받는건데 사용자가 많거나 트래픽이 높은 상황에서는 다운로드가 지연될 수 있어요
다운로드가 아예 안되는 거라면 https://github.com/dc-koromo/e-archive에기서 index-metadata.compress를 직접 다운로드하고 index-metadata.zip으로 파일이름을 바꾼다음 압축해제해 Koromo Copy.exe가 있는 폴더에 넣어주세요
