### ISSUE TITLE
파일 최신화 먹통

### ISSUE THREAD

**Issue by acenoye3** [rollrat/koromo-copy-windows#41]
![제목 없음](https://user-images.githubusercontent.com/60225523/72993878-7712cc00-3e39-11ea-9f68-bbfc96af05d4.png)

간만에 파밍 좀 하려고 싱글벙글 하면서 켰는데 최신 데이터가 안나오길래 

깃헙와서 최신버전 받아서 켰는데 그래도 최신 데이터가 안뜨네요...

보니까 가장 최신 파일이 1월 7일꺼 ㄷㄷ

index-metadata.compress 직접 깃헙에서 다운해서 zip으로 바꾸고 압축 풀어서 안에 넣는 방법도 써봤는데 그대로....ㅠㅠ

**Comment by kirin952020** [comment]
저도 이 증상이 있더라구요 ㅠㅠ
